name: Labels

on:
  schedule:
    - cron: 0 0 * * 6 # https://crontab.guru/#0_0_*_*_6
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  sync:
    permissions:
      contents: read
    name: Sync
    runs-on: ubuntu-latest
    env:
      GITHUB_APP_ID: ${{ secrets.RW_GITHUB_APP_ID }}
      GITHUB_APP_INSTALLATION_ID: ${{ secrets[format('RW_GITHUB_APP_INSTALLATION_ID_{0}', matrix.workspace)] || secrets.RW_GITHUB_APP_INSTALLATION_ID }}
      GITHUB_APP_PEM_FILE: ${{ secrets.RW_GITHUB_APP_PEM_FILE }}
      TF_WORKSPACE: ipfs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialize scripts
        run: npm install && npm run build
        working-directory: scripts
      - name: Add need/author-input label
        run: node lib/actions/add-need-author-input-label-to-all-repos.js
        working-directory: scripts
